# Generated by Django 3.0.5 on 2020-04-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_job',
            name='job_description',
            field=models.TextField(),
        ),
    ]
