# Generated by Django 3.0.5 on 2020-05-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200430_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_job',
            name='company_url',
            field=models.CharField(default='default_url', max_length=200),
        ),
        migrations.AlterField(
            model_name='saved_job',
            name='job_id',
            field=models.CharField(max_length=150),
        ),
    ]
