# Generated by Django 3.0.5 on 2020-05-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200501_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_job',
            name='company_url',
            field=models.CharField(max_length=200),
        ),
    ]
